"use no memo";

import FramesTimeline from "../../../timeline";

// Builder de JSX para `<FramesTimeline/>`. Espejo del builder de
// `memoizedLayerAnimation.jsx` con la misma lista de props.
export function renderFramesTimeline(props) {
  return (
    <FramesTimeline
      updateLayerZIndex={props.updateLayerZIndex}
      moveLayerToPosition={props.moveLayerToPosition}
      moveGroupToLayer={props.moveGroupToLayer}
      moveGroupToPosition={props.moveGroupToPosition}
      layers={props.layers}
      addLayer={props.addLayer}
      deleteLayer={props.deleteLayer}
      moveLayerUp={props.moveLayerUp}
      moveLayerDown={props.moveLayerDown}
      toggleLayerVisibility={props.toggleLayerVisibility}
      renameLayer={props.renameLayer}
      clearLayer={props.clearLayer}
      activeLayerId={props.activeLayerId}
      setActiveLayerId={props.setActiveLayerId}
      pixelGroups={props.pixelGroups}
      selectedGroup={props.selectedGroup}
      selectedPixels={props.selectedPixels}
      createPixelGroup={props.createPixelGroup}
      deletePixelGroup={props.deletePixelGroup}
      getLayerGroups={props.getLayerGroups}
      selectPixelGroup={props.selectPixelGroup}
      clearSelectedGroup={props.clearSelectedGroup}
      renamePixelGroup={props.renamePixelGroup}
      toggleGroupVisibility={props.toggleGroupVisibility}
      setSelectedPixels={props.setSelectedPixels}
      handleSelectGroup={props.handleSelectGroup}
      dragOffset={props.dragOffset}
      setSelectionCoords={props.setSelectionCoords}
      setSelectionActive={props.setSelectionActive}
      setCroppedSelectionBounds={props.setCroppedSelectionBounds}
      autoCropSelection={props.autoCropSelection}
      setOriginalPixelColors={props.setOriginalPixelColors}
      setDragOffset={props.setDragOffset}
      setTool={props.setTool}
      clearCurrentSelection={props.clearCurrentSelection}
      getHierarchicalLayers={props.getHierarchicalLayers}
      getMainLayers={props.getMainLayers}
      getGroupLayersForParent={props.getGroupLayersForParent}
      selectionActive={props.selectionActive}
      selectAllCanvas={props.selectAllCanvas}
      duplicateLayer={props.duplicateLayer}
      frames={props.frames}
      currentFrame={props.currentFrame}
      frameCount={props.frameCount}
      createFrame={props.createFrame}
      setActiveFrame={props.setActiveFrame}
      deleteFrame={props.deleteFrame}
      duplicateFrame={props.duplicateFrame}
      saveCurrentFrameState={props.saveCurrentFrameState}
      getFramesInfo={props.getFramesInfo}
      renameFrame={props.renameFrame}
      syncWithCurrentFrame={props.renameFrame}
      toggleLayerVisibilityInFrame={props.toggleLayerVisibilityInFrame}
      getLayerVisibility={props.getLayerVisibility}
      toggleOnionSkin={props.toggleOnionSkin}
      setOnionSkinConfig={props.setOnionSkinConfig}
      setOnionSkinFrameConfig={props.setOnionSkinConfig}
      getOnionSkinFrameConfig={props.getOnionSkinFrameConfig}
      getOnionSkinPresets={props.getOnionSkinFrameConfig}
      applyOnionSkinPreset={props.applyOnionSkinPreset}
      getOnionSkinInfo={props.getOnionSkinFrameConfig}
      onionSkinEnabled={props.onionSkinEnabled}
      showOnionSkinForLayer={props.showOnionSkinForLayer}
      clearOnionSkinLayerFilter={props.clearOnionSkinLayerFilter}
      onionSkinSettings={props.onionSkinSettings}
      setFrameDuration={props.setFrameDuration}
      getFrameDuration={props.getFrameDuration}
      getFrameRate={props.getFrameRate}
      setDefaultFrameRate={props.setDefaultFrameRate}
      defaultFrameDuration={props.defaultFrameDuration}
      setFrameOpacity={props.setFrameOpacity}
      getFrameOpacity={props.getFrameOpacity}
      framesResume={props.framesResume}
      setFramesResume={props.setFramesResume}
      externalCanvasRef={props.externalCanvasRef}
      viewportOffset={props.viewportOffset}
      viewportWidth={props.viewportWidth}
      viewportHeight={props.viewportHeight}
      zoom={props.zoom}
      isPlaying={props.isPlaying}
      setIsPlaying={props.setIsPlaying}
      eyeDropperColor={props.eyeDropperColor}
    />
  );
}
